name: Django CI/CD

on: [push, pull_request]
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run lint with flake8
        run: flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: habits_db
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
        #        options: >-
        #          --health-cmd pg_isready
        #          --health-interval 10s
        #          --health-timeout 5s
        #          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: test-key
          DEBUG: True
          DATABASE_NAME: habits_db
          DATABASE_USER: django_user
          DATABASE_PASSWORD: django_password
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
        run: |
          python manage.py test
          coverage run --source='.' manage.py test
          coverage report

    # Сборка образа и отправка на Docker Hub проекта habits_api
    build:
      needs: test
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

        - name: Build Docker image
          run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/habits-api:${{ github.sha }} .

        - name: Push Docker image to Docker Hub
          run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/habits-api:${{ github.sha }}


    # Деплой с Docker Hub проекта habits-api
    deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

        - name: Deploy to Server
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            docker stop habits-api || true # останавливаем старый контейнер если он есть
            docker rm habits-api || true # удаляем старый контейнер если он есть
            # скачиваем и запускаем контейнер с указанием сети. В .env нужно указать IP-адрес контейнера PostgreSQL
            docker run -d --name habits-api --env-file .env --network lms-drf_default -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/habits-api:${{ github.sha }}
            EOF
